### ISSUE TITLE
[Request] AutoSell 

### ISSUE THREAD

**Issue by Projecki** [GC-spigot/Tokens#11]
**Describe the feature**
Like clip's AutoSell but built into Tokens and supported up to latest version of minecraft.
https://www.spigotmc.org/resources/autosell.2157/

clip doesn't update his plugins anymore. AutoSell is a pretty essential feature of most prison server, and having it built into tokens would set it apart from competing plugins and also would literally be the only option for 1.16 server owners as there aren't any plugins out there that do it.

The majority of servers run on 1.16 spigot so this feature would surely bring in buyers as you'd have a monopoly on the AutoSell feature 👍

**Comment by Firosee** [comment]
Bad idea, this is a pickaxe tokens plugin, not a prison core.

Also, its actually a minority of servers which are ran on 1.16, alot of them are still on 1.12.2 as it is the most stable version at the moment. I would love to see autosell alternative, but i dont think it should be added into tokens, as it is not meant to be a prison core plugin.

**Comment by Projecki** [comment]
Incorrect, 1.12.2 servers represent 11.7% of spigot servers, while 1.16.x represents 55.9% of spigot servers.

Source: https://bstats.org/global/bukkit

Your not a prison core argument would be invalidated, in my opinion, by the fact that tokens includes autopickup. I think it would be a simple change that could be hooked up with the mine regions created with Tokens so that it will only autosell when mining within those regions.

**Comment by Projecki** [comment]
Also noteworthy that VK's TokenEnchant, the expressed main competitor of Tokens, includes an AutoSell enchant.

**Comment by Firosee** [comment]
Yes, an addon for said enchantment, i think if it was to be made into an enchant addon it should be fine, but i dont think it should be hard coded into the plugin.

Also, im shocked by that data, i was under the impression that alot more people used 1.12.2, thats interesting.

**Comment by EwansXD** [comment]
I'm asuming most of those 1.16.x servers are survival servers and not large scale servers with lots of plugins etc.

IMO, this would be a great addon further down the line.

**Comment by myiume** [comment]
> Incorrect, 1.12.2 servers represent 11.7% of spigot servers, while 1.16.x represents 55.9% of spigot servers.
> 
> Source: https://bstats.org/global/bukkit
> 
> Your not a prison core argument would be invalidated, in my opinion, by the fact that tokens includes autopickup. I think it would be a simple change that could be hooked up with the mine regions created with Tokens so that it will only autosell when mining within those regions.

the Auto pickup is a feature necessary for the efficiency of the server. Without it, you would have terrible performance, as the block break events would trigger a ton of chain reactions and updates that would lower the TPS of the server in case of custom enchantments that alter the vanilla behaviour. See shockwave or nuke for example.

As for AutoSell, the latest dev build seems to be okay. We tested it extensively and the integration with Tokens works just fine. We'll take into consideration adding this as a feature, but at this point, AutoSell works as intended.

**Comment by Projecki** [comment]
AutoSell does not work with Netherite tools on the latest version. That is the functionality it is missing for me. Sigh... such a simple fix being neglected.

**Comment by Firosee** [comment]
Thats something that is easily fixable with clip though, have you actually properly got ahold of him? Try catch and tag him when he makes his tags in his clip-pings channel, as thats how i always get my replies from him, as you catch him as he is in that exact channel.

**Comment by myiume** [comment]
AutoSell doesn't work with netherite tools because of the tools check? I can extend that if that's all you need ;)

**Comment by myiume** [comment]
There is no need for now to implement this into our enchants plugin. As Firosee mentioned, it is not a prison core.

In case support for AutoSell dies completely, we might make a plugin like it, but separately.
