### ISSUE TITLE
[Issue] Error

### ISSUE THREAD

**Issue by Sellinq** [GC-spigot/Tokens#12]
**Describe the bug**
When Nuke Enchantment procs

**To Reproduce**
Mine a block with nuke

**Screenshots / Video**
https://paste.helpch.at/avakelufif.cs

**Server Information (please complete the following information):**
 - Minecraft Version [e.g. kSpigot Paperspigot fork 1.12.2]
- Plugin Version [e.g. Tokens 2.7.7 Latest Nuke Enchant addon]

**Comment by myiume** [comment]
Issue fixed already. The new API changes caused some issues with the API call of EZBlocks. The hotfix has been applied and will be released on spigot with the new version most likely tomorrow.
