### ISSUE TITLE
Token pay does not work

### ISSUE THREAD

**Issue by Firosee** [GC-spigot/Tokens#15]
**Describe the bug**
Title says it all, token pay or withdraw doesn't work, says the command does not exist anymore.

**To Reproduce**
./te pay

**Screenshots / Video**
https://gyazo.com/7ad74b7034ce8a33a228b2802425ad99

**Server Information (please complete the following information):**
 - Minecraft Version 1.12.2
- Plugin Version Latest

**Comment by EwansXD** [comment]
Pay does not work, however withdraw works fine.

**Comment by myiume** [comment]
![image](https://user-images.githubusercontent.com/3586926/94365331-9fde1600-00d8-11eb-943e-03d23106eeda.png)

this looks fine to me. Can you help me reproduce this?

**Comment by myiume** [comment]
Ah yes, so you are saying that the pay command does not work. But you have admin permission. As an admin, you should use the /tokens add command. You have different commands as an admin, and pay is not one of them, as on the admin command list, it is replaced by /tokens add. I have added the pay as an alias for add on the admin side as well, so you guys can use that as an admin. Do recall that it will only act as "add", and will not have a balance requirement on the sender side.

**Comment by Firosee** [comment]
You should remove this feature, it should not change commands if you are an admin. There is no need to make it do that, i want to pay people from my balance, not from an admin command, and i dont want to have to deop myself everytime to do that.

**Comment by myiume** [comment]
Will be added during command rework.
