### ISSUE TITLE
[Issue] TPS Drops caused by powerful enchantments - Nuke/Shockwave

### ISSUE THREAD

**Issue by Sellinq** [GC-spigot/Tokens#16]
**Describe the bug**
Causes huge tps drops

**To Reproduce**
Mine with nuke or shockwave

**Screenshots / Video**
https://paste.helpch.at/iseyehubih.cs

**Server Information (please complete the following information):**
 - Minecraft Version [e.g. PaperSpigot Fork 1.12.2]
- Plugin Version [Tokens 2.7.8]

**Comment by myiume** [comment]
I honestly don't think the Shockwave enchant is actually causing issues. the Nuke one will be updated soon to make some optimizations. But Shockwave is already properly optimized and using FAWE for making the block sets on a region. The only way that will not cause issues is if we set the FAWE as lazy, which will certainly not give you the intended effect of a nuke.

**Comment by myiume** [comment]
Improvements have been done on the drops part. This should improve performance for those explosive enchants greatly.

Please report if you still get issues with those enchants after the 2.8.6 version
