### ISSUE TITLE
[Request] Mines by pcpsells support 

### ISSUE THREAD

**Issue by Aarpn** [GC-spigot/Tokens#17]
**Describe the feature**
https://www.spigotmc.org/resources/mines-%C2%BB-1-7-1-16-2-%E2%80%A2-unique-features-%E2%80%A2-api.63552/

Please add support for this plugin.

**Comment by myiume** [comment]
pcpSells API does not have a way for me to handle the block breaks. Will work with the PCPSells developer. But until that gets a bit of support, not much I can do about it.

**Comment by myiume** [comment]
Implemented.
