### ISSUE TITLE
[Request] Public API

### ISSUE THREAD

**Issue by Projecki** [GC-spigot/Tokens#20]
**Describe the feature**
Release a public api so that we can take do things such as calculate how many and what type of blocks are destroyed by tokens for the purpose of autoselling blocks (since clip's autosell doesn't function fully on 1.16)

Or re-release Solo's auto sell pickaxe enchants.

**Comment by myiume** [comment]
@Projecki not even the dev 1.10 version of Autosell?

The enchants are in the works.

**Comment by Projecki** [comment]
Correct Myiume, their dev version claims to work on 1.16 with diamond tools and below only. Even then, I haven't gotten it to work at all and have not received support from them yet.

**Comment by myiume** [comment]
API has been released publicly on spigot. 
https://www.spigotmc.org/resources/tokens-api.85210/
