### ISSUE TITLE
[Issue] KeyFinder conflicting with FAWE enchants

### ISSUE THREAD

**Issue by BluueJay** [GC-spigot/Tokens#21]
**Describe the bug**
KeyFinder works fine standalone, however whenever any FAWE enchants on the pickaxe proc, it will intensely spam the level-specific rewards. Changing `enchant.configuration.blocks-explode.enabled` to true/false makes no difference.

**To Reproduce**
In order to replicate this error, have more than two level specific rewards configured. You may use - https://pastebin.com/hkSJ5Jq4

KeyFinder will execute the rewards fine, until a FAWE enchant procs.

**Screenshots / Video**
N/A

**Server Information**
 - Server/MC version: 1.16.3 (latest Tuinity) 
 - Tokens version: [2.8.4](https://www.spigotmc.org/resources/⚡%EF%B8%8F-tokens-⚡%EF%B8%8F-40-enchantments-⭕-expansions-⭕-1-8-1-16-3-20-off.79668/update?update=364514) (latest)
 - FAWE version: Build 377 (latest)

**Comment by BluueJay** [comment]
A possible workaround could be to limit the number of rewards per configurable amount of milliseconds a player can receive.

**Comment by BluueJay** [comment]
When you take the `keyfinder.yml` pastebin I posted, reduce the cap to 5 and remove all configured level-rewards after 5 (and restart server), the problem goes away. Suggests that keyfinder doesn't work past a certain level with FAWE enchants.

**Comment by myiume** [comment]
Hi BluueJay, so the rewards proc multiple times for each block broken with FAWE? Like Shockwave?

**Comment by BluueJay** [comment]
> Hi BluueJay, so the rewards proc multiple times for the blocks broken with FAWE? 
> 
> 
> 
> Shockwave triggers KeyFinder multiple times, evaluating chance for each broken block, correct?

Correct except it seems the chance is also improperly calculated when a FAWE enchant procs, the rewards are severely spammed on each FAWE proc.

**Comment by myiume** [comment]
I'll modify the ExplodeEvent so it only triggers once and gives you all of the rewards, instead of proc-ing multiple times.

**Comment by myiume** [comment]
Issue has been fixed in Enchant version 3.0
