### ISSUE TITLE
[Request] Block-blacklist for FAWE enchants

### ISSUE THREAD

**Issue by BluueJay** [GC-spigot/Tokens#22]
**Describe the feature**
_A clear and concise description of what you want to happen._

FAWE enchants work very efficiently and nicely, although it can conflict with 'lucky block' type plugins such as MineCrates from clip. Almost over half the time a Sphered or Shockwave will destroy the chest or lucky block and not allow the player to mine them for rewards.

I suggest there be a way to blacklist items from being 'exploded' for enchants like Sphered, Shockwave, Detonate etc so that they can be interacted with manually by the player.

**Comment by Firosee** [comment]
+1

**Comment by Firosee** [comment]
I am also having this issue with minecrates from clip, for example, : https://gyazo.com/79101a55ae0111f65104b8d65a76e475

**Comment by Firosee** [comment]
I would change this from a feature request to an issue personally.

**Comment by myiume** [comment]
Not an issue. The enchant works as intended. But yeah, I can look into adding a blacklist for certain items.

**Comment by Firosee** [comment]
How is it not an issue? It is not compatable with other plugins which is causing other plugins to break. I can see how you may see it as a suggestion as technically it is adding something, but i would class this as an issue.

**Comment by myiume** [comment]
Added in latest dev version. Will release soon after further testing.

**Comment by myiume** [comment]
Contact me on discord for a copy if you want to test it @BluueJay
