### ISSUE TITLE
No message being shown to players when they get given tokens via te add command.

### ISSUE THREAD

**Issue by Firosee** [GC-spigot/Tokens#23]
can you make a message get sent to a player if someone does ./te add <player> <amount> admin command, saying like "You was given 1x tokens", as currently no message shows up so they have no idea if they get tokens or not via things like crates and that

**Comment by Firosee** [comment]
Completed in TokensV2.jar dev build sent on 09/10/2020 @ 9:40PM GMT.

**Comment by myiume** [comment]
Yeah. Will also add this to the public version once I get the messages system reworked a bit.
