### ISSUE TITLE
If you drop your tool with speed or haste enchant, it does not get removed.

### ISSUE THREAD

**Issue by Firosee** [GC-spigot/Tokens#24]
**Describe the bug**
If you throw out your pickaxe (using q or whatever keybind you have drop set too) with any enchantment on it such as speed or haste, it will not get removed from your effects list and will permanently stay applied to your effects list. 

**To Reproduce**
No video needed

**Screenshots / Video**
No screenshots needed

**Server Information (please complete the following information):**
 - Minecraft Version: paper 1.12.2
- Plugin Version Latest dev build sent via dms.

**Comment by myiume** [comment]
Working on a fix for all potion enchants. Speed, Haste, Nightvision, JumpBoost and others. Both levels of effect and keeping the effect on drop/swapping items.

**Comment by myiume** [comment]
All of the potion enchants have been completely reworked. All interactions with inventory/hotbar/dropping/picking up will now properly register.
