### ISSUE TITLE
[Issue] Laser does not work on 1.16.3

### ISSUE THREAD

**Issue by Projecki** [GC-spigot/Tokens#26]
**Describe the bug**
Laser does not work.

**To Reproduce**
Apply laser to a pick and mine.

Video below has Laser 250 on a pick, I also bump the proc up to 0.9 and still nothing.

**Screenshots / Video**
https://i.gyazo.com/aa9f8dd1ab1dabf2a6c837b7ca63d190.gif

**Server Information (please complete the following information):**
 - Tuinity 1.16.3
- Tokens 2.8.4

**Comment by myiume** [comment]
Issue fixed. Will be released with the next Enchantment version.
