### ISSUE TITLE
[Issue] Nuke does not work on 1.16.3

### ISSUE THREAD

**Issue by Projecki** [GC-spigot/Tokens#27]
**Describe the bug**
Nuke will give blocks but will not destroy the entire mine.

https://i.gyazo.com/e4e2464078a8c54b4eae474c625de830.gif

**Server Information (please complete the following information):**
 - Tuinity 1.16.3
- tokens 2.8.4

no errors

**Comment by myiume** [comment]
Nuke has a "virtual" configuration. Are you sure that is turned off? It is meant not to do anything, considering the amount of blocks it will have to process.
