### ISSUE TITLE
[Issue] Giving does not work on 1.16.3

### ISSUE THREAD

**Issue by Projecki** [GC-spigot/Tokens#28]
Giving enchant doesn't proc.

Tuinity 1.16.3
Tokens 2.8.4

**Comment by Projecki** [comment]
Right as I logged off this error spammed my console, not sure if related.

https://pastebin.com/GPm2RUkt

**Comment by Projecki** [comment]
Restarting server allowed for Giving to function properly. 

This error has popped up once before, I sent it to Myiume previously.

Note that a bit before this I had an issue where I could remove items from the tokens menu. This has happened a few times before and I know others have had this issue but I'm not sure how to consistently recreate it.

**Comment by myiume** [comment]
This was an unrelated error. Got fixed.
