### ISSUE TITLE
[Issue] KeyFinder doesn't apply to the pickaxe on 1.16.3

### ISSUE THREAD

**Issue by Projecki** [GC-spigot/Tokens#29]
Applying KeyFinder to your pickaxe does nothing

https://i.gyazo.com/93835a0f6171604a0c35b54e9db3d389.gif

 - Tuinity 1.16.3
- Tokens 2.8.4

**Comment by myiume** [comment]
The command won't work if you use a level that is greater than the one you have configured on the enchant configuration.
