### ISSUE TITLE
[Request] Prestige enchants

### ISSUE THREAD

**Issue by ImAlexGG** [GC-spigot/Tokens#30]
I m suggesting a new feature for the server that allows to prestige enchantments, so when a player reach max level for example jackhammer instead of breaking on layers it will break two but it will be reset to 1 so you will have the same chances to break in normal than in prestige the only thing that changes is the layers or token miner if you prestige it your tokens gains double so if with max level you get 25 per block with max level of prestige you get 50

**Comment by SeiryuCrazy** [comment]
Hello mister almighty creator Also to the issue of prestige in enchants I could add an addition type improvements in a jackhammer that becomes a type of crossmine but the concept would not be that if not that for each persecution we suppose 5 a new line is added but not jackhammer type I mean a cross mine line Prestige 1 a cross, Prestige 2 a cross with 1 vertical line and so on up to prestige 5 with a star-shaped mine break the line or type * something like that (this broken would be vertically not horizontally)

**Comment by SeiryuCrazy** [comment]
Another suggestion that I could give you from me in so many years using a plugin similar to this one would be LuckyBlocks by breaking sponges or modifying the lore of ponder-type items, adding more detail, more work there, also leaving it more aesthetic in the sense of being able to separate the custom enchantments from the vanilla or give also variables in the lore type ezblocks and stuff

**Comment by Sellinq** [comment]
Noted this is great and all but this isnt really what tokens was built for

**Comment by Firosee** [comment]
Yeah i agree with Sellinq here, i dont think this should be added.

**Comment by myiume** [comment]
None of these features do really have a purpose in the Enchantments plugin. Integration with such features can be done, but not as an integrated feature into our plugin. This is not a prison core.
