### ISSUE TITLE
[Issue] Tokens Gui Issue

### ISSUE THREAD

**Issue by Aarpn** [GC-spigot/Tokens#33]
**Describe the bug**
https://gyazo.com/e54b4c469b623e0c2b23c8c02340ccf1 

Also, this possibly is whats leading this to be spammed in my console https://pastebin.com/X02jQMHD

**To Reproduce**
Idk, all I know is, I got latest tokens, and when I click a slot in a random gui, it will enchant if there is an enchant in that slot,

**Screenshots / Video**
https://gyazo.com/e54b4c469b623e0c2b23c8c02340ccf1

**Server Information (please complete the following information):**
 - Minecraft Version [e.g. PaperSpigot 1.8.8] Spigot 1.8.8
- Plugin Version [e.g. 6.7.8] Tokens 2.8.5

**Comment by myiume** [comment]
As we have discussed, issue caused by OpenINV. will look into finding a solution for this, but considering OpenINV does this to other plugins as well, it might be an issue on their side.
