### ISSUE TITLE
[Issue]

### ISSUE THREAD

**Issue by Aarpn** [GC-spigot/Tokens#35]
**Describe the bug**
When using Jump enchant, if you swap from the pickaxe with jump to anything even your hand, it will keep the jump boost there

**To Reproduce**
not esacly needed 

**Screenshots / Video**
https://gyazo.com/ce1462080197166d4f6c51a5b54cfef7

**Server Information (please complete the following information):**
 - Minecraft Version [e.g. PaperSpigot 1.8.8] Spigot 1.8.8
- Plugin Version [e.g. 6.7.8] 2.8.5

**Comment by myiume** [comment]
Fixed with latest enchant version.
