### ISSUE TITLE
[Request] Interaction blacklist for actions to open menu

### ISSUE THREAD

**Issue by SladeHazard** [GC-spigot/Tokens#39]
**Describe the feature**
Add option to put blocks in a blacklist category. so if chests are in blacklist when people right-click their pickaxes  while looking at blacklist-category the enchant menu won't open.
This can be useful if you have right click set to open enchant menu
but if player accidentally right click chests or mine crates with a pickaxe the menu doesn't open.

**Comment by myiume** [comment]
Added in 2.9.1.
