### ISSUE TITLE
[Issue] BlockBreakEvent Exception

### ISSUE THREAD

**Issue by BluueJay** [GC-spigot/Tokens#40]
**Describe the bug**
_A clear and concise description of what the bug is._

Mining NETHER_QUARTZ on 1.16.3 server fires BlockBreak exceptions, this is messing with FAWE enchants as they're not procing when in vicinity of this block.

https://paste.debian.net/1168782/

Potentially useful info:

New ID for block (in 1.16.3): NETHER_QUARTZ_ORE

**To Reproduce**
N/A

**Screenshots / Video**
N/A

**Server Information (please complete the following information):**

- Server/MC version: 1.16.3 (latest Tuinity)
- Tokens version: 2.8.6 (latest)
- FAWE version: Build 377 (latest)

**Comment by myiume** [comment]
1.16.x mapping implemented in latest version. Thanks for reporting 👍
