### ISSUE TITLE
[Issue] Duplicated Enchants

### ISSUE THREAD

**Issue by MrBBubbles** [GC-spigot/Tokens#42]
**Describe the bug**
After creating a kit using essentials, retrieve the kit and enchant using tokens leads to duplicated enchants

**To Reproduce**
https://gyazo.com/9f3a3c60ed0f6d5dbfc160c47dadeeec

**Comment by myiume** [comment]
How do you reproduce it?

The exact kit configuration and what you have done afterwards?

It looks to me like the item doesn't hide the vanilla enchantments so you get both custom Fortune and vanilla fortune.

**Comment by myiume** [comment]
make sure you properly capitalize the enchant name in the configuration for kits. if it's "Efficiency" with a capital E in the config, make sure it's the same in the kit
