### ISSUE TITLE
[Enchant Request] Lightning

### ISSUE THREAD

**Issue by EwansXD** [GC-spigot/Tokens#43]
Breaks a column of blocks and strikes lightning at the location.

Configuration example:

enchant:
  configuration:
    custom-name: Lightning
    display: '&cLightning %level%'
    proc: 1.0
    effects:
      strike: true
      sound: true
    location: RANDOM # can be RANDOM or EXACT - RANDOM will chose a random location in region, EXACT will use the block broken location
    allowed-items:
    - DIAMOND_PICKAXE
    refundable: false
    permission:
      enabled: false
      value: tokens.enchant.Lightning
  levels:
    configuration:
      max-level: 250
      starting-price: 0
      cost-algorithm: (levels * 500) + startingPrice

**Comment by myiume** [comment]
This one already exists.
