### ISSUE TITLE
[Issue] Tokenskitaddon issues reset

### ISSUE THREAD

**Issue by Aarpn** [GC-spigot/Tokens#47]
**Describe the bug**
When trying to use tokens kit addon and making a kit with essentials then transfering that stuff to tokenskitaddon config, it then puts the enchants back to level 0 pretty much

**To Reproduce**
A way to reproduce the video

use the tokens kit addon plugin

**Screenshots / Video**
https://gyazo.com/b4031ae7b76799e978802ca50cdd9051

**Server Information (please complete the following information):**
 - Minecraft Version [e.g. PaperSpigot 1.8.8] spigot 1.8.8
- Plugin Version [e.g. 6.7.8] tokens 2.8.9

**Comment by myiume** [comment]
Make sure you capitalize the Enchant name properly. If it's called "Efficiency" make sure your enchant is properly named with the uppercase letter.
