### ISSUE TITLE
[Issue] KeyFinder block-explode option not registering

### ISSUE THREAD

**Issue by BluueJay** [GC-spigot/Tokens#49]
**_(Follow up of #21 KeyFinder issue)_**

I believe Myiume resolved an underlying issue with the Essentials command spam however when using a Crates plugin to give a player keys via command, they will still be spammed.

I'm curious to see that if keyfinder.yml config option `enchant.configuration.blocks-explode.enabled` is fixed, this bug may go away, as right now this option being changed to true/false has no affect.

**Describe the bug**
KeyFinder works great until a FAWE enchant procs, where the rewards [COMMAND] will be insanely spammed and causing TPS lag as it will fire an external plugins' command (such as giving a player keys 1000+ times in under a second).

**To Reproduce**
Use KeyFinder with more than 2 configured levels and mine with a pickaxe that has a FAWE enchant on it.

**Server Information (please complete the following information):**
- Server/MC version: 1.16.3 (Tuinity)
- Plugin Version 2.8.9 (latest)
- FAWE version 1.16-377;5e67c1b

**Comment by myiume** [comment]
I believe this issue can be solved by making it have a different command that only executes once per trigger?

**Comment by BluueJay** [comment]
> I believe this issue can be solved by making it have a different command that only executes once per trigger?

        rewards:
          '1':
            chance: 12
            commands:
            - '[MESSAGE] &7You received a &b&lCOMMON KEY'
            - '[COMMAND] cr give to %player% common 1'

The command /cr is part of CratesReloaded which gives the player a defined amount of keys.

Due to the FAWE procs ignoring the calculation (%) of chance, it just insanely spams the '[COMMAND]' portion of the rewards configuration for its' level.

I'm confused on what I'd have to change it to, to make it execute once per trigger.

**Comment by myiume** [comment]
clearly. because it will only trigger once if it doesn't use explode. The issue is triggering multiple commands for each block on explode. KeyFinder needs an extention so it only triggers it once.

**Comment by myiume** [comment]
Completely reworked KeyFinder.
