### ISSUE TITLE
[Issue] Lores duplicating 

### ISSUE THREAD

**Issue by EwansXD** [GC-spigot/Tokens#5]
**Describe the bug**

Lores duplicating when buying from enchant GUI

**To Reproduce**

Buy enchants from enchant GUI

**Screenshots / Video**

https://gyazo.com/94f69b60c02df47a840a32a393a74f22

**Server Information (please complete the following information):**
 - Minecraft Version: 1.12.2
- Plugin Version: Dev build (sent to me by Myiume)

**Comment by Firosee** [comment]
I can vouch for this, i am getting this issue too:

https://gyazo.com/9eb9faa43ce3f375b7daebaa4b4066d6

**Comment by EwansXD** [comment]
Update has fixed the issue, tested and confirmed.

https://www.spigotmc.org/resources/%E2%9A%A1%EF%B8%8F-tokens-%E2%9A%A1%EF%B8%8F-40-enchantments-%E2%AD%95-expansions-%E2%AD%95-1-8-1-16-3-20-off.79668/updates
