### ISSUE TITLE
[Request] Update KeyFinder

### ISSUE THREAD

**Issue by EwansXD** [GC-spigot/Tokens#50]
- Make it so if max level is higher than configured levels, it just gives the max level rewards
- Add math parsing to commands

**Comment by myiume** [comment]
Planned feature already :) Thx for making it into an issue :)

**Comment by myiume** [comment]
Added math parsing to commands. The level rewards will be implemented as a general feature for all the enchants that have per level rewards, when the Enchants API will be remade.
