### ISSUE TITLE
[Issue] Placeholder Issue

### ISSUE THREAD

**Issue by Sellinq** [GC-spigot/Tokens#53]
**Describe the bug**
Placeholder not working and a placeholder returning the wrong numbers

**To Reproduce**
A way to reproduce the video
Parsing the placeholders in game

**Screenshots / Video**
![image](https://user-images.githubusercontent.com/52636787/100626431-b80f2300-331d-11eb-880c-dd0514d056d1.png)

**Server Information (please complete the following information):**
 - Minecraft Version [e.g. PaperSpigot 1.8.8]
- Plugin Version [e.g. 6.7.8]
1.8.8 and 1.12.2 both tested
Latest Tokens 2.9.1

**Comment by Sellinq** [comment]
Latest Tokens

**Comment by myiume** [comment]
Fixed. Will be added in the next release.
