### ISSUE TITLE
Tokens + KitsAddon

### ISSUE THREAD

**Issue by imsalinas** [GC-spigot/Tokens#54]
**Describe the bug**
Tokens doesn't recognize the lore of an existing enchant on a kit and duplicates the lore when enchanted.

**To Reproduce**
Enchant an item with any Tokens enchant and make it a kit.
Redeem the kit and proceed to enchant it again and lore will be duplicated.

**Screenshots / Video**
https://www.youtube.com/watch?v=xZ3ltOd87iw

**Server Information (please complete the following information):**
 - Minecraft Version:
![mcversion](https://user-images.githubusercontent.com/74385959/101208061-3aa62400-3637-11eb-88e8-0402feb2db53.PNG)

- Plugin Version:
DEV Build Tokensv2_1.jar

**Comment by myiume** [comment]
As discussed in the support group, the addon works as intended. you guys were not using it properly I reckon. Will reopen this if this still remains an issue, but for now I see it working as intended.
