### ISSUE TITLE
[Issue] Duping of pickaxe and enchantment books in upgrade menu

### ISSUE THREAD

**Issue by dustinsbustin** [GC-spigot/Tokens#57]
**Describe the bug**
Instead of right clicking to open the menu with one click normally, double-clicking or drag-clicking causes the menu to open as if it was a regular chest and you can drop the items or put them in your inventory.

**To Reproduce**
Same as description.

**Screenshots / Video**
https://youtu.be/kr_iMD8yfII
https://youtu.be/kbgEn0V0u98

**Server Information (please complete the following information):**
- Minecraft Version [FoxSpigot 1.8.8 (Custom Premium Jar)]
- Plugin Version [2.9.1]

**Comment by GC-spigot** [comment]
Fixed
