### ISSUE TITLE
[Issue] Item hold event

### ISSUE THREAD

**Issue by Aarpn** [GC-spigot/Tokens#6]
**Describe the bug**

Error in console: https://pastebin.com/pzdHSkzU

**To Reproduce**
A way to reproduce the video

Idk, all I know is it happens maybe when a enchant procs, or something

**Screenshots / Video**

nothing to record or screenshot

**Server Information (please complete the following information):**
 - Minecraft Version spigot 1.8.8
- Plugin Version 6.7.8 (happens in latest tho as tested it)

**Comment by myiume** [comment]
User has reported this does not happen anymore. Also the stacktrace there does not match the latest enchantment source code. Issue closed. Please reopen if it happens again.
