### ISSUE TITLE
Enchantments do not work

### ISSUE THREAD

**Issue by TheNameIsBrent** [GC-spigot/Tokens#61]
**Describe the bug**
The only enchant that works is efficiency and fortune on ores. When I have shockwave installed and set the proc to 1.0 and upped my pickaxe to the max level, the enchant does not work.

Neither does the fortune enchant give me random tokens.

**To Reproduce**
I did nothing. Thats the problem. No errors, nothing.

**Screenshots / Video**
Not applicable

**Server Information (please complete the following information):**
 - Minecraft Version git-Paper-314 (1.16.4)
- Plugin Version 2.9.2

**Comment by myiume** [comment]
what is the max level of your fortune and efficiency?

**Comment by jozefbonnar** [comment]
I think I'm having the same but slightly different issue, I have max JackHammer and Shockwave but when I mine a block with a max proc set, it does mine the mine with jackhammer, but I can't see the changes until I leave and join back again then I can see the changes, its like a visual glitch

**Comment by GC-spigot** [comment]
> I think I'm having the same but slightly different issue, I have max JackHammer and Shockwave but when I mine a block with a max proc set, it does mine the mine with jackhammer, but I can't see the changes until I leave and join back again then I can see the changes, its like a visual glitch

This is a FastAsyncWorldEdit bug, try updating - I believe it has been fixed recently with last update
