### ISSUE TITLE
[Issue] Receivers of /tokens add/pay get no messages

### ISSUE THREAD

**Issue by BluueJay** [GC-spigot/Tokens#62]
**Describe the bug**
_A clear and concise description of what the bug is._

When the console executes /tokens add or pay, the receiver does not get a message showing that they have gotten the tokens. 
I've tried resetting the messages.yml file after using the latest tokens version on 1.16.4.

**To Reproduce**
_A way to reproduce the video_

N/A

**Screenshots / Video**
_If applicable, add screenshots to help explain your problem._

N/A

**Server Information (please complete the following information):**
 - Minecraft Version: Tuinity 1.16.4 (latest)
- Plugin Version: 2.9.2

**Comment by GC-spigot** [comment]
Try updating, doesn't happen in testing
