### ISSUE TITLE
[Issue] Visual block glitch when using jackhammer

### ISSUE THREAD

**Issue by jozefbonnar** [GC-spigot/Tokens#67]
**Describe the bug**
When using jackhammer I can't see the blocks broken unless I leave and join 

**To Reproduce**
Using JackHammer 250 and efficiency 250
https://cdn.discordapp.com/attachments/705035107861266482/810566584857788466/2021-02-14_17-38-53.mp4

**Screenshots / Video**
https://cdn.discordapp.com/attachments/705035107861266482/810566584857788466/2021-02-14_17-38-53.mp4

**Server Information (please complete the following information):**
 - Minecraft Version: git-paper-391 MC 1.15.2
- Plugin Version 2.9.1

**Comment by GC-spigot** [comment]
Fixed for next update
