### ISSUE TITLE
Take out books

### ISSUE THREAD

**Issue by TheNameIsBrent** [GC-spigot/Tokens#71]
**Describe the bug**
Sometimes you get the book from the menu whenever you try to upgrade your pickaxe. Maybe because of lag or something else. They are not unstealable. 

**To Reproduce**
I don't really know when it happens, it just happens sometimes. And sometimes you can take out 5 books and sometimes only 1.

**Server Information (please complete the following information):**
 - Minecraft Version [Paper on Bukkit 1.16.4-R0.1-SNAPSHOT]
- Plugin Version [Tokens-1.3.1]

**Comment by GC-spigot** [comment]
Fixed
