### ISSUE TITLE
Nuke enchant permissions

### ISSUE THREAD

**Issue by TheNameIsBrent** [GC-spigot/Tokens#72]
**Describe the bug**
The Nuke enchant permissions don't work. Whenever I set the permissions the true and assign the permission, everyone can still use it.

**Server Information (please complete the following information):**
 - Minecraft Version [Paper on Bukkit 1.16.4-R0.1-SNAPSHOT]
- Plugin Version [Tokens-1.3.1] (and nuke enchant latest version)

**Comment by GC-spigot** [comment]
Tokens 1.3.1? That's half a year old version at least
