### ISSUE TITLE
Tokens Withdraw Bug

### ISSUE THREAD

**Issue by TheNameIsBrent** [GC-spigot/Tokens#75]
**Describe the bug**
When you withdraw 10000 tokens, you will only get the amount that fits in your inventory and it doesn't drop the rest. It doesn't drop the tokens that don't fit in your inventory.

**Server Information (please complete the following information):**
 - Minecraft Version [Paper on Bukkit 1.16.4-R0.1-SNAPSHOT]
- Plugin Version [Tokens-1.3.1]

**Comment by GC-spigot** [comment]
Fixed
