### ISSUE TITLE
Add placeholder with kMB formatting

### ISSUE THREAD

**Issue by Firosee** [GC-spigot/Tokens#9]
**Describe the bug**
In the old versions of tokens, there was a placeholder to show like "99k", that placeholder now just shows as "99,000".

**To Reproduce**
Test the placeholders using ./papi parse me <placeholder>

**Screenshots / Video**
https://gyazo.com/25fc237f2aadca26f22bc72c612e9e99

**Server Information (please complete the following information):**
 - Minecraft Version *PaperSpigot 1.12.2*
- Plugin Version *latest dev build*

**Comment by myiume** [comment]
This is not an issue. But an enhancement. Will be added as a different placeholder that uses the kMB formatting. :) Already planned

**Comment by Firosee** [comment]
I mean i would say it was a bug because it was like that before it got taken over, but okay.

**Comment by myiume** [comment]
Feature implemented. Will be released in next update
